#server.port=8761
#eureka.instance.hostname=192.168.2.226
#eureka.client.registerWithEureka=false
#eureka.client.fetchRegistry=false
#eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:8769/eureka/
server:
  port: 8769
spring:
  application:
    name: eureka-server
  profiles: peer2
eureka:
  instance:
    hostname: 192.168.2.226
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://${eureka.instance.hostname}:8769/eureka/
#    register-with-eureka: false
#    fetch-registry: false
