#server.port=8761
#eureka.instance.hostname=192.168.2.226
#eureka.client.registerWithEureka=false
#eureka.client.fetchRegistry=false
#eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:8769/eureka/
server:
  port: 8761
spring:
  application:
    name: eureka-server
  profiles: peer1
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/,http://192.168.2.226:8769/eureka/
#    register-with-eureka: false
#    fetch-registry: false
